name: Github Docker Image CI
on: push
jobs:
  chromium:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
    - run: | 
        docker build -t ghcr.io/james-martinez/alpine-browser/chromium:latest .
        docker push ghcr.io/james-martinez/alpine-browser/chromium:latest
